# Generated by Django 3.2.16 on 2022-11-17 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients_and_notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='send',
            new_name='send_status',
        ),
    ]
