# Generated by Django 3.2.16 on 2022-11-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_and_notes', '0003_alter_message_send_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
